### ISSUE TITLE
Ionic serve will not run

### ISSUE THREAD

**Issue by KevinBurton** [smichelotti/ionic2-google-maps-test#2]
Running 'ionic serve' gives me
Running 'serve:before' npm script before serve

> ionic-hello-world@ watch /Users/rebeccaannburton/Projects/ionic2-google-maps-test
> ionic-app-scripts watch

module.js:472
    throw err;
    ^

Error: Cannot find module 'reflect-metadata'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/rebeccaannburton/Projects/ionic2-google-maps-test/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:4:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

**Comment by smichelotti** [comment]
You're getting this with the latest version of the course code download (i.e., for RC4)? And you have the latest version of the Ionic CLI? What does this produce? 

```
ionic info
```
